version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bmc08gt
  assignees:
  - bmc08gt
