name: CI
on:
  pull_request:
concurrency:
  # Limit concurrency to 1 for PRs. 'main' concurrency isn't limited.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CI: true
  JAVA_VERSION: 17

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master

      - name: Setup Java env
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Setup Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Decode Google Services JSON file
        uses: timheuer/base64-to-file@v1
        id: google_services_json_file
        with:
          fileName: google-services.json
          fileDir: ./app/src
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}
          
      - name: Setup BugSnag API Key
        run: echo BUGSNAG_API_KEY=\"${{ secrets.BUGSNAG_API_KEY }}\" > ./local.properties

      - name: Setup Mixpanel API Key
        run: echo MIXPANEL_API_KEY=\"${{ secrets.MIXPANEL_API_KEY }}\" >> ./local.properties

      - name: Run tests
        run: bundle exec fastlane android test
